commerce_payment.commerce_payment_gateway.plugin.stripe:
  type: commerce_payment_gateway_configuration
  mapping:
    publishable_key:
      type: string
      label: 'Publishable key'
    secret_key:
      type: string
      label: 'Secret key'
    enable_credit_card_icons:
      type: boolean
      label: 'Enable credit card icons'
